format_version: 9
common:
  testing_stages: &testing_stages
    - setup-and-test:
        resources:
          - hq
          - windows
          - arcmap10-6
        artifacts:
          - test:
              source: "junit-output"
          # - test:
          #<artifact type="build" src="target/**/*.xml" />

        tasks:
          - exec:
              command: cmd
              arguments:
                - "/c"
                - "C:/py27arcgis106/ArcGIS10.6/python.exe"
                - "-m"
                - virtualenv
                - env
          - exec:
              command: "env/Scripts/python.exe"
              arguments:
              - "-m"
              - pip
              - install
              - "-r"
              - requirements-dev.txt
          - exec:
              command: "env/Scripts/python.exe"
              arguments:
              - "-m"
              - pip
              - install
              - "-e"
              - "."
          - exec:
              command: "mkdir"
              arguments:
              - "junit-reports"
          - exec:
              command: "env/Scripts/python.exe"
              arguments:
              - "-m"
              - flake8
          - exec:
              command: "env/Scripts/python.exe"
              arguments:
              - "-m"
              - coverage
              - run
              - "-m"
              - xmlrunner
              - discover
              - "mapactionpy_arcmap/tests"
              - "-o"
              - "junit-reports"
          - exec:
              command: "coveralls"


pipelines:
  unittest-mapy-arcmap:
    group: mapactionpy_arcmap
    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    materials:
      mapy-controller:
        scm: 7b37b961-6310-45e4-9968-25a17397b6a3
    stages:
      - *testing_stages
    #<artifact type="build" src="target/**/*.xml" />
#           <artifact type="test" src="target/junit-output" dest="junit"/>

    # stages:
    #   - *testing_stages
    #   - deploy:
    #       resources:
    #         - hq
    #         - windows
    #       artifacts:
    #         - build:
    #             source: default-cmf/deploy-to-fileserver.log
    #       tasks:
    #         - exec:
    #             command: default-cmf/deploy-to-fileserver.cmd
